/**
 * Kalodata TikTok 电商数据 API 的结构化接口规格。
 *
 * 这是接口文档的唯一事实来源：CLI 的 `--help` 帮助文本、参数类型解码、必填参数
 * 校验都从这里派生。修改任一接口时只需改这里。
 * @module @deepseek-ai/dsh-kalodata-demo/spec
 */

/** 官方 API 基地址；所有接口均为 POST + JSON，请求头携带 `secret-key` 认证。 */
export const DEFAULT_BASE_URL = 'https://www.kalodata.com'

/** 一个请求参数。`type` 取自文档（string/integer/number/boolean/array<...>/object）。 */
export interface ParamSpec {
  readonly name: string
  readonly type: string
  readonly required: boolean
  readonly example: string
  readonly description: string
  /** 数值参数的可选范围约束（文档未写明但真实接口强制）。 */
  readonly min?: number
  readonly max?: number
}

/** 一个响应字段（含 `data.` 前缀的嵌套字段）。 */
export interface ResponseFieldSpec {
  readonly name: string
  readonly type: string
  readonly description: string
}

/** 一个接口：路径、标题、请求参数与响应字段。 */
export interface EndpointSpec {
  readonly command: string
  readonly title: string
  readonly path: string
  readonly params: readonly ParamSpec[]
  readonly response: readonly ResponseFieldSpec[]
}

/** 所有接口共用的四个必填参数（文档中 8 个接口描述完全一致）。 */
const SHARED_PARAMS: readonly ParamSpec[] = [
  {
    name: 'region',
    type: 'string',
    required: true,
    example: 'US',
    description: '数据国家代码，例如 US、BR、MX、ID、JP、MY、PH、SG、TH、VN、GB、ES、DE、FR、IT。',
  },
  {
    name: 'language',
    type: 'string',
    required: true,
    example: 'en-US',
    description: '响应中文本字段的语言。目前支持 zh-CN、en-US、id-ID、th-TH、vi-VN、es-ES、ja-JP、pt-BR、ko-KR、fr-FR。',
  },
  {
    name: 'currency',
    type: 'string',
    required: true,
    example: 'USD',
    description: '收入和价格字段的货币单位。目前支持 CNY、USD、IDR、VND、THB、MYR、JPY、PHP、GBP、SGD、MXN、EUR、BRL。',
  },
  {
    name: 'date_range',
    type: 'string',
    required: true,
    example: 'last7Day',
    description: '日期范围。接受命名范围（lastDay、last7Day、last30Day、last60Day、last90Day、last180Day、last365Day）、yyyy-MM-dd~yyyy-MM-dd 格式的自然日期范围，或自然月 yyyy-MM。部分接口会限制此集合，请参阅各接口说明。',
  },
]

/** 四个榜单接口共用的排序与分页参数（含被排序对象本身的 `sort_field`）。 */
const RANK_PARAMS: readonly ParamSpec[] = [
  {
    name: 'sort_field',
    type: 'object',
    required: false,
    example: '{"field":"revenue","type":"DESC"}',
    description: '排序规范。field 接受响应中的任何数值字段；type 为 ASC 或 DESC。默认为 {"field":"revenue","type":"DESC"}。',
  },
  {
    name: 'sort_field.field',
    type: 'string',
    required: false,
    example: 'revenue',
    description: '排序字段名。支持接口返回的任何数值字段，例如 revenue、sales_volumn、revenue_growth_rate。',
  },
  {
    name: 'sort_field.type',
    type: 'string',
    required: false,
    example: 'DESC',
    description: '排序方向。',
  },
  {
    name: 'rank_field',
    type: 'string',
    required: false,
    example: 'revenue',
    description: '排序字段名称的旧版快捷方式；建议使用 sort_field。设置 sort_field 时将被忽略。',
  },
  {
    name: 'asc',
    type: 'boolean',
    required: false,
    example: 'false',
    description: '与 rank_field 配对的旧版升序标识。默认为 false（DESC）。',
  },
  {
    name: 'page_size',
    type: 'integer',
    required: false,
    example: '20',
    description: '页面大小。每次查询最多 100 条记录，默认为 10，最小为 5。',
    min: 5,
    max: 100,
  },
  {
    name: 'page_number',
    type: 'integer',
    required: false,
    example: '1',
    description: '页码，从 1 开始。',
  },
]

/** 达人榜单（creator/rank）特有的图片/类目开关。 */
const RANK_NEED_IMAGE_CATEGORY_PARAMS: readonly ParamSpec[] = [
  {
    name: 'need_image',
    type: 'integer',
    required: false,
    example: '1',
    description: '是否需要主图链接：0 = 不需要（默认），1 = 返回官方链接，2 = 返回 kalo_data 图片链接（需付费服务）。',
  },
  {
    name: 'need_category',
    type: 'integer',
    required: false,
    example: '0',
    description: '是否需要类目信息：0 = 不需要，1 = 需要。',
  },
  {
    name: 'need_ter_category',
    type: 'integer',
    required: false,
    example: '0',
    description: '是否需要三级类目信息：0 = 不需要，1 = 需要。',
  },
]

/** 接口注册表：顺序即 `kalodata --help` 概览中的展示顺序。 */
export const ENDPOINTS: readonly EndpointSpec[] = [
  {
    command: 'creator/detail',
    title: '获取达人详情',
    path: '/openapi/v1/tiktok/creator/detail',
    params: [
      ...SHARED_PARAMS,
      {
        name: 'creator_id',
        type: 'string',
        required: true,
        example: '6937492675021095937',
        description: '要查询的达人 ID。',
      },
      {
        name: 'category_ids',
        type: 'array<integer>',
        required: false,
        example: '[700645, 223]',
        description: '将收入归因限制为指定的类目 ID。',
      },
      {
        name: 'shop_id',
        type: 'string',
        required: false,
        example: '7495634116320922282',
        description: '将收入归因限制为指定店铺的商品。',
      },
      {
        name: 'need_extra',
        type: 'boolean',
        required: false,
        example: 'false',
        description: '是否需要额外信息。',
      },
    ],
    response: [
      { name: 'success', type: 'boolean', description: '请求是否成功' },
      { name: 'data', type: 'object', description: '达人数据对象' },
      { name: 'data.creator_id', type: 'string', description: '达人 ID' },
      { name: 'data.creator_nickname', type: 'string', description: '达人昵称' },
      { name: 'data.creator_handle', type: 'string', description: '达人用户名' },
      { name: 'data.creator_region', type: 'string', description: '达人国家/地区' },
      { name: 'data.creator_status', type: 'string', description: '达人身份。BELONGED_TO_SELLER = 店铺自有达人，INDEPENDENT = 独立联盟达人。' },
      { name: 'data.creator_belonged_shop_id', type: 'string', description: '达人所属店铺。如果达人是联盟达人则为空。' },
      { name: 'data.creator_bio', type: 'string', description: '个人主页达人简介，头部达人每日更新。' },
      { name: 'data.creator_contact_email', type: 'string', description: '达人邮箱' },
      { name: 'data.creator_contact_tiktok', type: 'string', description: '达人 TikTok 账号' },
      { name: 'data.creator_contact_whatsapp', type: 'string', description: '达人的 WhatsApp 账号' },
      { name: 'data.creator_contact_line', type: 'string', description: '达人 Line 账号' },
      { name: 'data.creator_contact_facebook', type: 'string', description: '达人 Facebook 账号' },
      { name: 'data.creator_contact_ins', type: 'string', description: '达人的 Instagram 账号' },
      { name: 'data.creator_contact_zalo', type: 'string', description: '达人 Zalo 账号' },
      { name: 'data.revenue', type: 'number', description: '选定时间范围内达人在选定类目下的销售收入' },
      { name: 'data.sales_volumn', type: 'integer', description: '选定时间范围内达人在选定类目下的销量' },
      { name: 'data.unit_price', type: 'number', description: '选定时间范围内达人在选定类目下的平均客单价' },
      { name: 'data.video_revenue', type: 'number', description: '选定时间范围内达人在选定类目下商品的视频销售收入' },
      { name: 'data.live_revenue', type: 'number', description: '选定时间范围内达人在选定类目下商品的直播销售收入' },
      { name: 'data.video_views', type: 'integer', description: '选定时间范围内达人的视频总播放量' },
      { name: 'data.live_views', type: 'integer', description: '选定时间范围内达人的直播总观看次数' },
      { name: 'data.live_gpm', type: 'number', description: '选定时间范围内达人直播销售的 GPM（千次观看收入）' },
      { name: 'data.video_gpm', type: 'number', description: '选定时间范围内达人视频销售的 GPM（千次观看收入）' },
      { name: 'data.new_followers', type: 'integer', description: '选定时间范围内达人新增粉丝数' },
      { name: 'data.video_number', type: 'integer', description: '选定时间范围内达人有播放量的视频数' },
      { name: 'data.live_number', type: 'integer', description: '选定时间范围内达人开播场次' },
      { name: 'data.shop_number', type: 'integer', description: '选定时间范围内达人合作的店铺数' },
      { name: 'data.product_number', type: 'integer', description: '选定时间范围内达人售出商品数' },
      { name: 'data.creator_followers', type: 'string', description: '达人粉丝数，每日更新' },
      { name: 'data.revenue_trend', type: 'array<number>', description: '选定时间范围内达人在选定类目下的销售收入趋势' },
      { name: 'data.top3_product_ids', type: 'array<string>', description: '选定时间范围内达人在选定类目下销量排名前 3 的商品 ID' },
      { name: 'message', type: 'string', description: '响应消息' },
      { name: 'debug', type: 'object', description: '调试信息' },
      { name: 'cached', type: 'boolean', description: '是否使用缓存数据' },
      { name: 'code', type: 'string', description: '响应状态码' },
    ],
  },
  {
    command: 'creator/rank',
    title: '获取达人榜单列表',
    path: '/openapi/v1/tiktok/creator/rank',
    params: [
      ...SHARED_PARAMS,
      ...RANK_PARAMS,
      {
        name: 'category_ids',
        type: 'array<integer>',
        required: false,
        example: '[700645, 223]',
        description: '已废弃，请使用 category_id_list。用于限制达人收入的类目 ID 列表。',
      },
      {
        name: 'category_id_list',
        type: 'string',
        required: false,
        example: '700645,223',
        description: '逗号分隔的类目 ID，优先于 category_ids。',
      },
      {
        name: 'shop_id',
        type: 'string',
        required: false,
        example: '7494965300835814281',
        description: '限制为与指定店铺合作的达人（任何挂载该店铺商品并有曝光的视频、直播或橱窗）。',
      },
      {
        name: 'product_id',
        type: 'string',
        required: false,
        example: '1729587769570529799',
        description: '限制为推广过指定商品的达人。',
      },
      {
        name: 'revenue_range',
        type: 'string',
        required: false,
        example: '100-1000',
        description: '成交金额区间筛选，货币单位与请求 currency 相同。也支持 <100 / >1000 格式。',
      },
      {
        name: 'creator_type',
        type: 'string',
        required: false,
        example: 'INDEPENDENT',
        description: '达人类型筛选。BELONGED_TO_SELLER = 卖家自有达人，INDEPENDENT = 独立联盟达人。',
      },
      {
        name: 'followers_range',
        type: 'string',
        required: false,
        example: '1000-10000',
        description: '粉丝数范围筛选器，也支持 <100 / >1000 格式。',
      },
      {
        name: 'engagement_rate',
        type: 'string',
        required: false,
        example: 'MEDIUM',
        description: '互动率区间。LOW = <8%，MEDIUM = 8%-20%，HIGH = >20%。',
      },
      {
        name: 'keyword',
        type: 'string',
        required: false,
        example: 'beauty',
        description: '达人搜索关键词。',
      },
      ...RANK_NEED_IMAGE_CATEGORY_PARAMS,
    ],
    response: [
      { name: 'success', type: 'boolean', description: '请求是否成功' },
      { name: 'data', type: 'array<object>', description: '达人数据列表' },
      { name: 'data.creator_id', type: 'string', description: '达人 ID' },
      { name: 'data.creator_nickname', type: 'string', description: '达人昵称' },
      { name: 'data.creator_handle', type: 'string', description: '达人用户名，带 @ 前缀的为 handle 名称' },
      { name: 'data.revenue', type: 'number', description: '达人成交金额' },
      { name: 'data.revenue_growth_rate', type: 'number', description: '达人成交金额增长率' },
      { name: 'data.content_views', type: 'string', description: '所选时间范围内达人内容播放量' },
      { name: 'data.creator_followers', type: 'string', description: '达人粉丝数，每日更新' },
      { name: 'data.sales_volumn', type: 'integer', description: 'Sales volume（销量）' },
      { name: 'data.video_revenue', type: 'number', description: '视频销售收入' },
      { name: 'data.live_revenue', type: 'number', description: '直播销售收入' },
      { name: 'data.category_list', type: 'array<string>', description: '前三类目' },
      { name: 'data.category_id_list', type: 'array<string>', description: '前三类目 ID' },
      { name: 'data.ter_category_list', type: 'array<string>', description: '前三个三级类目' },
      { name: 'data.ter_category_id_list', type: 'array<string>', description: '前三个三级类目 ID' },
      { name: 'message', type: 'string', description: '响应消息' },
      { name: 'debug', type: 'object', description: '调试信息' },
      { name: 'cached', type: 'boolean', description: '是否使用缓存数据' },
      { name: 'code', type: 'string', description: '响应状态码' },
    ],
  },
  {
    command: 'category/detail',
    title: '获取类目详情',
    path: '/openapi/v1/tiktok/category/detail',
    params: [
      ...SHARED_PARAMS,
      {
        name: 'category_id',
        type: 'string',
        required: true,
        example: '601450',
        description: '要查询的类目 ID。',
      },
    ],
    response: [
      { name: 'success', type: 'boolean', description: '请求是否成功' },
      { name: 'data', type: 'object', description: '类目数据对象' },
      { name: 'data.category_id', type: 'string', description: '类目 ID' },
      { name: 'data.category_name', type: 'string', description: '类目名称' },
      { name: 'data.revenue', type: 'number', description: '所选时间范围内类目收入' },
      { name: 'data.shop_number', type: 'integer', description: '所选时间范围内在该类目下有商品销售记录的店铺数' },
      { name: 'data.live_revenue', type: 'number', description: '所选时间范围内类目商品通过直播渠道的成交金额' },
      { name: 'data.video_revenue', type: 'number', description: '所选时间范围内类目商品通过视频渠道的成交金额' },
      { name: 'data.revenue_growth_rate', type: 'number', description: '所选时间范围内类目的增长率' },
      { name: 'data.average_shop_revenue', type: 'number', description: '所选时间范围内有在售商品店铺的平均收入' },
      { name: 'data.affiliate_revenue', type: 'number', description: '所选时间范围内类目商品通过联盟达人合作的订单金额' },
      { name: 'data.self_operate_revenue', type: 'number', description: '所选时间范围内类目商品通过店铺自有达人的订单金额' },
      { name: 'data.shopping_mall_revenue', type: 'number', description: '所选时间范围内类目商品通过商城渠道的订单金额' },
      { name: 'data.revenue_trend', type: 'array<number>', description: '所选时间范围内类目收入趋势' },
      { name: 'data.sale', type: 'integer', description: '所选时间范围内类目的销量' },
      { name: 'data.active_product_number', type: 'integer', description: '所选时间范围内在该类目下有商品销售记录的商品数' },
      { name: 'message', type: 'string', description: '响应消息' },
      { name: 'debug', type: 'object', description: '调试信息' },
      { name: 'cached', type: 'boolean', description: '是否使用缓存数据' },
      { name: 'code', type: 'string', description: '响应状态码' },
    ],
  },
  {
    command: 'category/rank',
    title: '获取类目榜单列表',
    path: '/openapi/v1/tiktok/category/rank',
    params: [
      ...SHARED_PARAMS,
      ...RANK_PARAMS,
      {
        name: 'category_ids',
        type: 'array<string>',
        required: false,
        example: '[601450]',
        description: '将结果限制为给定类目 ID 及其子类目。省略时包含所有类目。',
      },
      {
        name: 'category_level',
        type: 'integer',
        required: false,
        example: '1',
        description: '返回的类目层级。1 = 一级类目，2 = 二级类目，3 = 叶子类目。',
      },
      {
        name: 'revenue_range',
        type: 'string',
        required: false,
        example: '100-1000',
        description: '所选时间段内的成交金额区间筛选，货币单位与请求 currency 相同。也支持 <100 或 >1000 等开区间格式。',
      },
    ],
    response: [
      { name: 'success', type: 'boolean', description: '请求是否成功' },
      { name: 'data', type: 'array<object>', description: '类目数据列表' },
      { name: 'data.category_id', type: 'string', description: '类目 ID' },
      { name: 'data.category_name', type: 'string', description: '类目名称，根据不同的语言参数返回不同语言的类目名称' },
      { name: 'data.rank', type: 'integer', description: '类目排名' },
      { name: 'data.revenue', type: 'number', description: '所选时间范围内类目的总收入' },
      { name: 'data.sale', type: 'integer', description: '所选时间范围内类目的销量' },
      { name: 'data.revenue_growth_rate', type: 'number', description: '所选时间范围内类目的销量增长率' },
      { name: 'data.top3_shop_revenue_ratio', type: 'number', description: '对应类目中收入排名前 3 的店铺的收入占比' },
      { name: 'data.average_revenue', type: 'number', description: '类目中每家店铺的平均收入' },
      { name: 'message', type: 'string', description: '响应消息' },
      { name: 'debug', type: 'object', description: '调试信息' },
      { name: 'cached', type: 'boolean', description: '是否使用缓存数据' },
      { name: 'code', type: 'string', description: '响应状态码' },
    ],
  },
  {
    command: 'shop/detail',
    title: '获取店铺详情',
    path: '/openapi/v1/tiktok/shop/detail',
    params: [
      ...SHARED_PARAMS,
      {
        name: 'shop_id',
        type: 'string',
        required: true,
        example: '7494965300835814281',
        description: '要查询的店铺 ID。',
      },
      {
        name: 'category_ids',
        type: 'array<string>',
        required: false,
        example: '[601450]',
        description: '将收入归因限制为指定的类目 ID。',
      },
      {
        name: 'need_extra',
        type: 'boolean',
        required: false,
        example: 'false',
        description: '是否需要额外信息。',
      },
    ],
    response: [
      { name: 'success', type: 'boolean', description: '请求是否成功' },
      { name: 'data', type: 'object', description: '数据对象' },
      { name: 'data.shop_id', type: 'string', description: '店铺 ID' },
      { name: 'data.shop_name', type: 'string', description: '店铺名称' },
      { name: 'data.region', type: 'string', description: '店铺国家/地区（与请求的 region 值匹配）' },
      { name: 'data.revenue', type: 'number', description: '所选时间段内的店铺收入' },
      { name: 'data.shoppingmall_revenue', type: 'number', description: '所选时间段内通过商城渠道的店铺收入' },
      { name: 'data.self_account_revenue', type: 'number', description: '所选时间段内通过自营账号订单产生的店铺收入' },
      { name: 'data.affiliate_revenue', type: 'number', description: '所选时间段内通过联盟达人账号订单产生的店铺收入' },
      { name: 'data.sales_volumn', type: 'integer', description: '店铺销量，选定时间范围内的店铺商品总销量' },
      { name: 'data.unit_price', type: 'number', description: '所选时间段内店铺的平均单价' },
      { name: 'data.creator_number', type: 'integer', description: '在所选时间段内与店铺合作的联盟达人数量' },
      { name: 'data.product_number', type: 'integer', description: '所选时间段内店铺上架的商品数量' },
      { name: 'data.video_number', type: 'integer', description: '选定时间范围内产生曝光的带有店铺商品的视频数' },
      { name: 'data.live_number', type: 'integer', description: '选定时间范围内包含店铺商品的直播数' },
      { name: 'data.revenue_trend', type: 'array<number>', description: '所选时间段内的店铺收入趋势' },
      { name: 'data.top3_product_ids', type: 'array<string>', description: '所选时间段内排名前 3 的商品 ID' },
      { name: 'data.seller_type', type: 'string', description: '卖家类型' },
      { name: 'message', type: 'string', description: '响应消息' },
      { name: 'debug', type: 'object', description: '调试信息' },
      { name: 'cached', type: 'boolean', description: '是否使用缓存数据' },
      { name: 'code', type: 'string', description: '响应状态码' },
    ],
  },
  {
    command: 'shop/rank',
    title: '获取店铺榜单列表',
    path: '/openapi/v1/tiktok/shop/rank',
    params: [
      ...SHARED_PARAMS,
      ...RANK_PARAMS,
      {
        name: 'category_ids',
        type: 'array<string>',
        required: false,
        example: '[601450]',
        description: '将结果限制为在指定类目 ID 下销售的店铺。',
      },
      {
        name: 'revenue_range',
        type: 'string',
        required: false,
        example: '100-1000',
        description: '店铺收入区间筛选，货币单位与请求 currency 相同。也支持 <100 / >1000 格式。',
      },
      {
        name: 'shop_type',
        type: 'string',
        required: false,
        example: 'BRAND',
        description: '店铺类型筛选。BRAND = 品牌自营店，RETAILER = 零售店。',
      },
      {
        name: 'keyword',
        type: 'string',
        required: false,
        example: 'electronics',
        description: '店铺搜索关键词。',
      },
      {
        name: 'need_image',
        type: 'integer',
        required: false,
        example: '1',
        description: '是否需要主图链接：0 = 不需要（默认），1 = 返回官方链接，2 = 返回 kalo_data 图片链接（需付费服务）。',
      },
      {
        name: 'need_category',
        type: 'integer',
        required: false,
        example: '0',
        description: '是否需要类目信息：0 = 不需要，1 = 需要。',
      },
      {
        name: 'unit_price_range',
        type: 'string',
        required: false,
        example: '10-100',
        description: '店铺商品平均价格范围。',
      },
    ],
    response: [
      { name: 'success', type: 'boolean', description: '请求是否成功' },
      { name: 'data', type: 'array<object>', description: '店铺数据列表' },
      { name: 'data.shop_id', type: 'string', description: '店铺 ID' },
      { name: 'data.shop_name', type: 'string', description: '店铺名称' },
      { name: 'data.rank', type: 'integer', description: '在所选条件下根据排序标准获取的店铺排名' },
      { name: 'data.revenue', type: 'number', description: '店铺交易金额' },
      { name: 'data.sales_volumn', type: 'integer', description: '店铺销量，选定时间范围内的店铺商品总销量' },
      { name: 'data.revenue_growth_rate', type: 'number', description: '店铺交易金额增长率' },
      { name: 'data.unit_price', type: 'number', description: '所选时间范围内店铺的平均单价' },
      { name: 'data.shop_type', type: 'string', description: '店铺类型，分为零售店和品牌店' },
      { name: 'data.on_sell_product_count', type: 'integer', description: '在售商品数' },
      { name: 'data.affiliate_revenue', type: 'number', description: '所选时间段内通过联盟达人账号订单产生的店铺收入' },
      { name: 'data.self_promotion_revenue', type: 'number', description: '所选时间段内通过自营账号订单产生的店铺收入' },
      { name: 'data.shopping_mall_revenue', type: 'number', description: '所选时间段内通过商城渠道的店铺收入' },
      { name: 'data.image_url', type: 'string', description: '店铺图片链接' },
      { name: 'data.category_list', type: 'array<string>', description: '类目名称，根据不同的语言参数返回不同语言的类目名称' },
      { name: 'data.category_id_list', type: 'array<string>', description: '类目 ID' },
      { name: 'message', type: 'string', description: '响应消息' },
      { name: 'debug', type: 'object', description: '调试信息' },
      { name: 'cached', type: 'boolean', description: '是否使用缓存数据' },
      { name: 'code', type: 'string', description: '响应状态码' },
    ],
  },
  {
    command: 'product/detail',
    title: '获取商品详情',
    path: '/openapi/v1/tiktok/product/detail',
    params: [
      ...SHARED_PARAMS,
      {
        name: 'product_id',
        type: 'string',
        required: true,
        example: '1729587769570529799',
        description: '要查询的商品 ID。',
      },
      {
        name: 'need_image',
        type: 'integer',
        required: false,
        example: '1',
        description: '是否需要主图链接：0 = 不需要（默认），1 = 返回官方链接，2 = 返回 kalo_data 图片链接（需付费服务）。',
      },
      {
        name: 'need_extra',
        type: 'boolean',
        required: false,
        example: 'false',
        description: '是否需要额外信息。',
      },
    ],
    response: [
      { name: 'success', type: 'boolean', description: '请求是否成功' },
      { name: 'data', type: 'object', description: '商品数据对象' },
      { name: 'data.product_id', type: 'string', description: '商品 ID' },
      { name: 'data.product_region', type: 'string', description: '商品国家/地区' },
      { name: 'data.product_name', type: 'string', description: '商品名称' },
      { name: 'data.product_shop_id', type: 'string', description: '商品店铺 ID' },
      { name: 'data.pri_cate_id', type: 'string', description: '商品主类目 ID' },
      { name: 'data.sec_cate_id', type: 'string', description: '商品二级类目 ID' },
      { name: 'data.ter_cate_id', type: 'string', description: '商品三级类目 ID' },
      { name: 'data.max_price', type: 'number', description: '商品最高 SKU 价格' },
      { name: 'data.min_price', type: 'number', description: '商品最低 SKU 价格' },
      { name: 'data.revenue', type: 'number', description: '选定时间范围内的商品收入' },
      { name: 'data.video_revenue', type: 'number', description: '选定时间范围内的商品视频收入' },
      { name: 'data.live_revenue', type: 'number', description: '所选时间范围内商品的直播收入' },
      { name: 'data.sales_volumn', type: 'integer', description: '选定时间范围内的商品销量' },
      { name: 'data.creator_number', type: 'integer', description: '选定时间范围内推广过该商品的达人数' },
      { name: 'data.video_number', type: 'integer', description: '选定时间范围内推广过该商品的视频数' },
      { name: 'data.live_number', type: 'integer', description: '所选时间范围内推广该商品的直播数' },
      { name: 'data.delivery_type', type: 'string', description: '商品的履约模式' },
      { name: 'data.shopping_mall_revenue', type: 'number', description: '商城收入' },
      { name: 'data.commission_rate', type: 'number', description: '商品佣金率。值为百分点，即 1.0 = 1%' },
      { name: 'data.unit_price', type: 'number', description: '选定时间范围内的商品单价' },
      { name: 'data.product_review_count', type: 'integer', description: '商品评价数' },
      { name: 'data.launch_date', type: 'string', description: '商品发布日期' },
      { name: 'data.master_image_url', type: 'string', description: '主图链接' },
      { name: 'data.revenue_trend', type: 'array<number>', description: '所选时间段内的收入趋势' },
      { name: 'data.product_description', type: 'array<object>', description: '商品描述详情，为图文混合块。不可用时为空数组' },
      { name: 'message', type: 'string', description: '响应消息' },
      { name: 'debug', type: 'object', description: '调试信息' },
      { name: 'cached', type: 'boolean', description: '是否使用缓存数据' },
      { name: 'code', type: 'string', description: '响应状态码' },
    ],
  },
  {
    command: 'product/rank',
    title: '获取商品榜单',
    path: '/openapi/v1/tiktok/product/rank',
    params: [
      ...SHARED_PARAMS,
      ...RANK_PARAMS,
      {
        name: 'category_ids',
        type: 'array<string>',
        required: false,
        example: '[601450]',
        description: '将结果限制为指定的类目 ID。',
      },
      {
        name: 'shop_id',
        type: 'string',
        required: false,
        example: '7495634116320922282',
        description: '将结果限制为指定店铺。',
      },
      {
        name: 'creator_id',
        type: 'string',
        required: false,
        example: '7495634116320922282',
        description: '将结果限制为指定达人推广的商品。结合 shop_id，返回该达人在该店铺的列表。',
      },
      {
        name: 'video_id',
        type: 'string',
        required: false,
        example: '7495634116320922282',
        description: '返回给定视频挂载的商品。',
      },
      {
        name: 'livestream_id',
        type: 'string',
        required: false,
        example: '7495634116320922282',
        description: '返回指定直播间挂载的商品。',
      },
      {
        name: 'revenue_range',
        type: 'string',
        required: false,
        example: '1-10',
        description: '收入区间筛选，货币单位与请求货币相同。也支持 <10 / >1 格式。',
      },
      {
        name: 'is_affiliate',
        type: 'integer',
        required: false,
        example: '1',
        description: '联盟计划筛选。0 = 仅非联盟，1 = 仅联盟。',
      },
      {
        name: 'commission_rate',
        type: 'string',
        required: false,
        example: '15-35',
        description: '联盟商品佣金率筛选器。支持范围（15-35）、开放区间（<10、>=30）或单一比例。',
      },
      {
        name: 'is_tts_product',
        type: 'integer',
        required: false,
        example: '1',
        description: 'TTS（TikTok 全托管）商品筛选。1 = 仅全托管，0 = 仅自发货。',
      },
      {
        name: 'unit_price_range',
        type: 'string',
        required: false,
        example: '1-1000',
        description: '商品单价范围筛选器。',
      },
      {
        name: 'need_all',
        type: 'boolean',
        required: false,
        example: 'false',
        description: '若为 true，则包含在选定时间范围内无销量的商品。默认为 false（仅限有销量）。',
      },
      {
        name: 'delivery_type',
        type: 'string',
        required: false,
        example: 'local',
        description: '发货方式筛选。local = 国内发货，global = 跨境发货。',
      },
      {
        name: 'launch_date',
        type: 'string',
        required: false,
        example: '<7',
        description: '距离商品发布的天数。例如 <3 = 3 天内，<7 = 7 天内，>30 = 超过 30 天。',
      },
      {
        name: 'need_image',
        type: 'integer',
        required: false,
        example: '1',
        description: '是否需要主图链接：0 = 不需要（默认），1 = 返回官方链接，2 = 返回 kalo_data 图片链接（需付费服务）。',
      },
      {
        name: 'keyword',
        type: 'string',
        required: false,
        example: 'mobile phone',
        description: '关键词搜索。',
      },
      {
        name: 'need_extra',
        type: 'boolean',
        required: false,
        example: 'false',
        description: '是否需要额外信息，例如卖家名称、SKU 数量。',
      },
    ],
    response: [
      { name: 'success', type: 'boolean', description: '请求是否成功' },
      { name: 'data', type: 'array<object>', description: '商品数据列表' },
      { name: 'data.product_id', type: 'string', description: '商品 ID' },
      { name: 'data.product_name', type: 'string', description: '商品名称' },
      { name: 'data.revenue', type: 'number', description: '指定条件下完成的收入' },
      { name: 'data.commission_rate', type: 'number', description: '商品佣金率，热门商品每日更新' },
      { name: 'data.revenue_growth_rate', type: 'number', description: '商品收入增长率' },
      { name: 'data.sales_volumn', type: 'integer', description: '选定时间范围内的商品销量' },
      { name: 'data.unit_price', type: 'number', description: '选定时间范围内的商品单价' },
      { name: 'data.live_revenue', type: 'number', description: '所选时间范围内商品的直播收入' },
      { name: 'data.video_revenue', type: 'number', description: '选定时间范围内的商品视频收入' },
      { name: 'data.showcase_revenue', type: 'number', description: '橱窗收入' },
      { name: 'data.launch_date', type: 'string', description: '商品发布日期' },
      { name: 'data.master_image_url', type: 'string', description: '主图链接' },
      { name: 'data.seller_id', type: 'string', description: '卖家 ID' },
      { name: 'data.seller_name', type: 'string', description: '卖家名称' },
      { name: 'data.sku_count', type: 'string', description: 'SKU 数' },
      { name: 'message', type: 'string', description: '响应消息' },
      { name: 'debug', type: 'object', description: '调试信息' },
      { name: 'cached', type: 'boolean', description: '是否使用缓存数据' },
      { name: 'code', type: 'string', description: '响应状态码' },
    ],
  },
]

/** 按 command 精确查找接口。 */
export function findEndpoint(command: string): EndpointSpec | undefined {
  return ENDPOINTS.find(endpoint => endpoint.command === command)
}
